import Head from 'next/head'
import styles from '../styles/Home.module.css'
import mercadopago from 'mercadopago'
import useMercadoPago from '../lib/MercadoPago'
import { useEffect } from 'react'

export default function Home(props: any) {

  const mercadopago = useMercadoPago(process.env.NEXT_PUBLIC_MERCADO_PAGO_PUBLIC_KEY || '', {
    locale: 'pt-BR'
  });

  useEffect(() => {
    if (mercadopago) {
      mercadopago.checkout({
        preference: {
          id: props.preference_id
        },
        render: {
          container: '.checkout-container',
          label: 'Pagar',
        },
        theme: {
          headerColor: '#c0392b',
          elementsColor: '#c0392b'
        }
      })
    }
    return () => {
      const buttonContainer = document.querySelector('.checkout-container')
      const button = buttonContainer?.lastElementChild

      if (buttonContainer && button) {
        buttonContainer.removeChild(button)
      }
    }
  }, [mercadopago])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <code className={styles.code}>Para prosseguir com o checkout clique em pagar</code>
        <div className="checkout-container" />
      </main>
    </>
  )
}

export async function getServerSideProps(context: any) {
  // Adicione as credenciais
  mercadopago.configure({
    access_token: process.env.MERCADO_PAGO_ACCESS_TOKEN || '',

  });

  // Cria um objeto de preferência
  let preference = {
    items: [
      {
        id: '1234',
        title: 'Lightweight Paper Table',
        description: 'Inspired by the classic foldable art of origami',
        category_id: 'home',
        quantity: 1,
        currency_id: 'BRL',
        unit_price: 55.41
      }
    ],
    payer: {
      name: "Joao",
      surname: "Silva",
      email: "c6e3d57d-2f4e-45de-82e5-94ada8f5946e@email.webhook.site",
      date_created: "2015-06-02T12:58:41.425-04:00",
      phone: {
        area_code: "11",
        number: 44444444
      },

      identification: {
        type: "CPF",
        number: "19119119100"
      },

      address: {
        street_name: "Street",
        street_number: 123,
        zip_code: "06233200"
      }
    },
    back_urls: {
      success: "http://localhost:3000/",
      failure: "http://localhost:3000/",
      pending: "http://localhost:3000/"
    },
    auto_return: "approved",
  };

  const response = await mercadopago.preferences.create(preference)
  const preference_id = response.body.id
  return {
    props: {
      asd: 123,
      preference_id: preference_id
    },
  }
}